# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: matter.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmatter.proto\x12%viamlabs.service.matter_controller.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\";\n\x11\x43ommissionRequest\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n\x04\x63ode\x18\x02 \x01(\tR\x04\x63ode\"\xfd\x02\n\x12\x43ommissionResponse\x12\x17\n\x07node_id\x18\x01 \x01(\x05R\x06nodeId\x12G\n\x11\x64\x61te_commissioned\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x10\x64\x61teCommissioned\x12\x41\n\x0elast_interview\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\rlastInterview\x12+\n\x11interview_version\x18\x04 \x01(\x05R\x10interviewVersion\x12\x1c\n\tavailable\x18\x05 \x01(\x08R\tavailable\x12\x1b\n\tis_bridge\x18\x06 \x01(\x08R\x08isBridge\x12\x1e\n\nattributes\x18\x07 \x01(\tR\nattributes\x12:\n\x19last_subscription_attempt\x18\x08 \x01(\x02R\x17lastSubscriptionAttempt2\xe3\x01\n\x17MatterControllerService\x12\xc7\x01\n\nCommission\x12\x38.viamlabs.service.matter_controller.v1.CommissionRequest\x1a\x39.viamlabs.service.matter_controller.v1.CommissionResponse\"D\x82\xd3\xe4\x93\x02>\"</viamlabs/api/v1/service/matter_controller/{name}/commissionb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'matter_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MATTERCONTROLLERSERVICE.methods_by_name['Commission']._options = None
  _MATTERCONTROLLERSERVICE.methods_by_name['Commission']._serialized_options = b'\202\323\344\223\002>\"</viamlabs/api/v1/service/matter_controller/{name}/commission'
  _COMMISSIONREQUEST._serialized_start=118
  _COMMISSIONREQUEST._serialized_end=177
  _COMMISSIONRESPONSE._serialized_start=180
  _COMMISSIONRESPONSE._serialized_end=561
  _MATTERCONTROLLERSERVICE._serialized_start=564
  _MATTERCONTROLLERSERVICE._serialized_end=791
# @@protoc_insertion_point(module_scope)
